global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  #- job_name: "app"

    # Override global settings
   # scrape_interval: 5s

    #static_configs:
     # - targets: ["app:80"]

  - job_name: "raspberry"

    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.188.99:5000"]
